apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
  - name: demo-pod1
    image: edmondleung0724/edmondrepo:v1.0.0
    ports:
    - containerPort: 3000
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs
      mountPath: "/demo-nfs/pv-test"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-pvc
